services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ApplicationFirst_app
    volumes:
      - ./back:/var/www/html
    depends_on:
      - db
    networks:
      - symfony
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: ApplicationFirst_nginx
    ports:
      - "8080:80"
    volumes:
      - ./back:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - symfony
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: ApplicationFirst_db
    environment:
      POSTGRES_USER: alpha_user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: symfony
    ports:
      - "5433:5432"
    volumes:
      - ./docker/db_data:/var/lib/postgresql/data
    networks:
      - symfony
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    container_name: ApplicationFirst_jenkins
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ./docker/jenkins_data:/var/jenkins_data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - symfony
    restart: unless-stopped

  postgres-sonar:
    image: postgres:13
    container_name: ApplicationFirst_postgres_sonar
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpass
      POSTGRES_DB: sonarqube
    volumes:
      - ./docker/postgres_sonar_data:/var/lib/postgresql/data
    networks:
      - symfony
    restart: unless-stopped

  sonarqube:
    image: sonarqube:10.5-community
    container_name: ApplicationFirst_sonarqube
    depends_on:
      - postgres-sonar
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres-sonar:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonarpass
      SONAR_SEARCH_JAVAADDITIONALOPTS: "-Dnode.store.allow_mmap=false"
    volumes:
      - ./docker/sonarqube_data:/opt/sonarqube/data
      - ./docker/sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - symfony
    restart: unless-stopped

  mercure:
    image: dunglas/mercure
    container_name: ApplicationFirst_mercure
    ports:
      - "3000:80"
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'my-super-secret-mercure-publisher-key-at-least-256-bits'
      MERCURE_SUBSCRIBER_JWT_KEY: 'my-super-secret-mercure-subscriber-key-at-least-256-bits'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:4200
        anonymous
    networks:
      - symfony
    restart: unless-stopped

networks:
  symfony:
    driver: bridge
